### ISSUE TITLE
Proxy list not working

### ISSUE THREAD

**Issue by sergioteula** [clarketm/proxy-list#12]
The proxy list is not working, the content shows a 404 error:

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /proxy.txt was not found on this server.</p>
<hr>
<address>Apache/2.4.25 (Debian) Server at spys.me Port 80</address>
</body></html>
```

**Comment by TheBronx** [comment]
In fact it is not an error, that is the actual content of the **proxy-list.txt** file :disappointed: 
The last commit changed the file completely: https://github.com/clarketm/proxy-list/commit/73bc4b3e34eed30c9720d6bc00dc477683bbd1f8
That is the problem.

**Comment by sergioteula** [comment]
Yes, you're right... I hope it's fixed soon. Thanks!

**Comment by bodzilla** [comment]
Hope OP fixes this soon!

**Comment by achillesrasquinha** [comment]
As a temporary fix! Use this proxy-list.txt file

```
$ https://raw.githubusercontent.com/clarketm/proxy-list/a9f2/proxy-list.txt
```

**Comment by bodzilla** [comment]
> As a temporary fix! Use the previous commit, proxy-list.txt file
> 
> ```
> $ https://raw.githubusercontent.com/clarketm/proxy-list/a9f2/proxy-list.txt
> ```
> ```
> curl -sSf "https://raw.githubusercontent.com/clarketm/proxy-list/a9f2/proxy-list.txt" | sed '1,3d; $d; s/\s.*//; /^$/d' > proxy-list.txt
> ```

Thanks for this! Much appreciated.

**Comment by achillesrasquinha** [comment]
@clarketm :)

**Comment by clarketm** [comment]
The proxy list is back online. I will take this as a cue to add addition validation in the job that scrapes these proxies ... since ultimately stale data is better than no data.

**Comment by sergioteula** [comment]
@clarketm thanks a lot!

**Comment by numinato** [comment]
Hi all! Thanks for caching the proxies! Since your site is not updated at the moment: you could use the Twitter link where the proxies are posted (this one is still up and updated). Cheers!
