### ISSUE TITLE
Corupted extracting

### ISSUE THREAD

**Issue by chnz2k** [clarketm/proxy-list#15]
Dear sir,
i just saw in the proxy list some sort of wrong proxy format like :
[+] Proxy BTC:BTC .
[+] Proxy ETC:ETC .
[+] Proxy BCH:BCH .
[+] Proxy LTC:LTC .
[+] Proxy IP:IP .
this is not a proxy format ofc hope u check your proxy list sources

**Comment by clarketm** [comment]
@chnz2k - thanks for the notification. I updated the [command](https://github.com/clarketm/proxy-list/blob/master/README.md#download) in README to match explicitly on `IP:PORT` rather than deleting a set amount of lines which should resolve the issue.
