### ISSUE TITLE
spys.one has removed the pl.txt source

### ISSUE THREAD

**Issue by abreksa4** [clarketm/proxy-list#5]
Looks like the source has dropped support for the plain-text version.

Looks like the first commit with the new 404 page is: https://github.com/clarketm/proxy-list/commit/984fdad842581bf2a6d862f3e08f236a6961d8b9

**Comment by clarketm** [comment]
@abreksa4 - thanks for the notification. I have reverted `master` to the last commit before the 404. I should have a resolution within the next day or so. Thanks again for bringing this to my attention.

**Comment by clarketm** [comment]
@abreksa4 – the URL has been updated. Thanks again for catching this!

**Comment by abreksa4** [comment]
@clarketm No problem, thanks for the quick fix.
